env:
  browser: true
  es2021: true
extends: airbnb
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  import/prefer-default-export: 0
  react/react-in-jsx-scope: 0
  react/function-component-definition: 0
  react/prop-types: 0
